INSERT INTO `users` (`user_id`, `email`, `password`, `created_at`, `updated_at`, `is_deleted`, `username`, `gender`, `trend`, `height`, `weight`) VALUES
(1, 'test@example.com', 'hashed_password', NOW(), NOW(), 0, 'テストユーザー', NULL, NULL, NULL, NULL);

-- items 테ーブル INSERT (generated from converted_final.xlsx)
START TRANSACTION;

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (2, 1, 1, 'コットン', 'ユニクロ', 'カジュアル、きれいめ', '夏-秋', '半袖、クルーネック', 1, 1, '半袖、クルーネック', '/static/images/1/clothes/gazou01.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (16, 2, 1, '綿', 'UNIQLO', 'カジュアル', '夏', '半袖、クルーネック', 1, 1, '半袖、クルーネック', '/static/images/1/clothes/gazou02.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (11, 12, 1, '綿', 'UNIQLO', 'カジュアル', '夏', '半袖、クルーネック', 1, 1, '半袖、クルーネック', '/static/images/1/clothes/gazou03.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (1, 12, 1, '綿', 'UNIQLO', 'カジュアル', '夏', '半袖、クルーネック', 1, 1, '半袖、クルーネック', '/static/images/1/clothes/gazou04.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 12, 1, 'コットン', 'UNIQLO', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 1, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou05.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (16, 12, 1, 'コットン', 'UNIQLO', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 1, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou06.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (8, 1, 1, 'コットン', 'MUHET', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 1, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou07.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (1, 2, 1, 'コットン', 'POLO', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 1, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou08.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 19, 1, 'コットン', 'OLIVE des OLIVE', 'カジュアル、かわいい', '春-秋-冬', '長袖、クルーネック', 1, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou09.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 15, 1, 'コットン', 'FRED PERRY', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 1, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou10.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (10, 4, 1, 'コットン', 'BLANK FICELLE', 'カジュアル、きれいめ', '春-秋', '長袖', 2, 1, '長袖', '/static/images/1/clothes/gazou11.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (13, 14, 1, 'コットン', 'POLO', 'カジュアル、きれいめ', '春-秋', '長袖', 2, 1, '長袖', '/static/images/1/clothes/gazou12.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (7, 4, 1, 'コットン', 'Starting Over', 'カジュアル、きれいめ', '春-秋', '長袖', 2, 1, '長袖', '/static/images/1/clothes/gazou13.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (12, 1, 1, 'コットン', '無印良品', 'カジュアル、きれいめ', '春-秋', '長袖', 2, 1, '長袖', '/static/images/1/clothes/gazou14.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (5, 1, 1, 'コットン', '無印良品', 'カジュアル、きれいめ', '春-秋', '長袖', 2, 1, '長袖', '/static/images/1/clothes/gazou15.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'UNIQLO', 'カジュアル', '春-秋-冬', '長袖', 2, 1, '長袖', '/static/images/1/clothes/gazou16.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 15, 1, 'ポリエステル', 'POLO', 'カジュアル、きれいめ', '春-秋', '長袖、リボンタイ', 2, 1, '長袖、リボンタイ', '/static/images/1/clothes/gazou17.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (2, 6, 1, 'ポリエステル', 'apres jour', 'カジュアル、かわいい', '春-秋', '長袖、リボン', 2, 1, '長袖、リボン', '/static/images/1/clothes/gazou18.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (1, 1, 1, 'ポリエステル', 'm.f.editorial', 'フォーマル', '春-秋', '長袖', 3, 1, '長袖', '/static/images/1/clothes/gazou19.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (12, 1, 1, 'ポリエステル', 'TAKA-Q', 'フォーマル', '春-秋', '長袖', 3, 1, '長袖', '/static/images/1/clothes/gazou20.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (2, 15, 1, 'コットン', 'FRED PERRY', 'カジュアル、きれいめ', '春-秋-冬', '長袖', 4, 1, '長袖', '/static/images/1/clothes/gazou21.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 15, 1, 'コットン', 'FRED PERRY', 'カジュアル、きれいめ', '春-秋-冬', '長袖', 4, 1, '長袖', '/static/images/1/clothes/gazou22.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 15, 1, 'コットン', 'U.S.POLO', 'カジュアル、きれいめ', '夏', '半袖', 4, 1, '半袖', '/static/images/1/clothes/gazou23.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 15, 1, 'ポリエステル', 'EIMY ISTOIRE', 'カジュアル、きれいめ', '春-秋-冬', '長袖', 4, 1, '長袖', '/static/images/1/clothes/gazou24.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (2, 6, 1, 'ニット', 'CALNAMUR', 'カジュアル', '春-秋-冬', '長袖', 5, 1, '長袖', '/static/images/1/clothes/gazou25.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (4, 15, 1, 'ニット', 'POLO', 'カジュアル、Vネック', '春-秋-冬', '長袖', 5, 1, '長袖', '/static/images/1/clothes/gazou26.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (2, 2, 1, 'ポリエステル', '無印良品', 'カジュアル', '春-秋-冬', '長袖', 5, 1, '長袖', '/static/images/1/clothes/gazou27.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 12, 1, 'ポリエステル', 'GU', 'カジュアル', '春-秋-冬', '長袖', 5, 1, '長袖', '/static/images/1/clothes/gazou28.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 15, 1, 'ポリエステル', 'SNIDEL', 'カジュアル', '春-秋-冬', '長袖', 5, 1, '長袖', '/static/images/1/clothes/gazou29.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, 'ウール', 'select MOCA by son', 'カジュアル、きれいめ', '春-秋-冬', '長袖、ケーブル', 5, 1, '長袖、ケーブル', '/static/images/1/clothes/gazou30.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 12, 1, 'ウール', 'JACKROSE', 'カジュアル', '春-秋-冬', '長袖', 5, 1, '長袖', '/static/images/1/clothes/gazou31.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (10, 12, 1, 'ウール', 'LILY BROWN', 'カジュアル、きれいめ', '春-秋-冬', '長袖', 5, 1, '長袖', '/static/images/1/clothes/gazou32.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (6, 1, 1, 'ウール', '無印良品', 'カジュアル、きれいめ', '春-秋-冬', 'クルーネック', 6, 1, 'クルーネック', '/static/images/1/clothes/gazou33.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ウール', '無印良品', 'カジュアル、きれいめ', '春-秋-冬', 'クルーネック', 6, 1, 'クルーネック', '/static/images/1/clothes/gazou34.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, '綿', 'GU', 'カジュアル', '春-秋-冬', 'フードあり', 7, 1, 'フードあり', '/static/images/1/clothes/gazou35.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (16, 1, 1, '綿', 'GU', 'カジュアル', '春-秋-冬', 'フードあり', 7, 1, 'フードあり', '/static/images/1/clothes/gazou36.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (10, 15, 1, '綿', 'NICE CLAUP', 'カジュアル', '春-秋-冬', 'フードあり、チャックあり', 7, 1, 'フードあり、チャックあり', '/static/images/1/clothes/gazou37.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 12, 1, '綿', 'GU', 'カジュアル', '春-秋-冬', 'フードあり', 7, 1, 'フードあり', '/static/images/1/clothes/gazou38.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'GU', 'カジュアル', '春-秋-冬', '長袖', 8, 1, '長袖', '/static/images/1/clothes/gazou39.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (7, 1, 1, 'ポリエステル', 'GU', 'カジュアル', '春-秋-冬', '長袖', 8, 1, '長袖', '/static/images/1/clothes/gazou40.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 12, 1, 'ポリエステル', 'GU', 'カジュアル', '春-秋-冬', '長袖', 8, 1, '長袖', '/static/images/1/clothes/gazou41.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (6, 1, 1, 'ニット', '無印良品', 'カジュアル', '春-秋-冬', '長袖、Ｖネック', 9, 1, '長袖、Ｖネック', '/static/images/1/clothes/gazou42.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ニット', 'UNIQLO', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 9, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou43.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (14, 1, 1, 'ニット', 'UNIQLO', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 9, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou44.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ニット', 'CRANK', 'カジュアル、リボン、かわいい', '春-秋-冬', '長袖、クルーネック', 9, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou45.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (7, 1, 1, 'ニット', 'depond', 'カジュアル', '春-秋-冬', '長袖、クルーネック', 9, 1, '長袖、クルーネック', '/static/images/1/clothes/gazou46.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'ニット', 'OLIVE des OLIVE', 'かわいい', '春-秋-冬', '長袖、丈は短め', 9, 1, '長袖、丈は短め', '/static/images/1/clothes/gazou47.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ニット', 'NICE CLAUP', 'かわいい', '春-秋-冬', '長袖、シャギー、Vネック', 9, 1, '長袖、シャギー、Vネック', '/static/images/1/clothes/gazou48.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 5, 1, 'ポリエステル', 'apres jour', 'かわいい', '春-秋-冬', '長袖', 10, 1, '長袖', '/static/images/1/clothes/gazou49.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (7, 1, 1, 'ニット', 'SNIDEL', 'かわいい、きれいめ', '春-秋-冬', '長袖、シャギー', 10, 1, '長袖、シャギー', '/static/images/1/clothes/gazou50.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'ポリエステル', 'adidas', 'カジュアル', '春-秋-冬', '長袖', 11, 1, '長袖', '/static/images/1/clothes/gazou51.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, 'ポリエステル', 'OLIVE des OLIVE', 'カジュアル、かわいい', '春-秋-冬', '長袖', 11, 1, '長袖', '/static/images/1/clothes/gazou52.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'mushwear', 'カジュアル', '春-秋-冬', '長袖', 11, 1, '長袖', '/static/images/1/clothes/gazou53.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, '綿', 'UNIQLO', '', '春-夏-秋-冬', '', 12, 1, '', '/static/images/1/clothes/gazou54.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, '綿', 'UNIQLO', '', '春-夏-秋-冬', '', 12, 1, '', '/static/images/1/clothes/gazou55.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, '綿', 'UNIQLO', '', '春-夏-秋-冬', '', 13, 1, '', '/static/images/1/clothes/gazou56.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (1, 1, 1, 'ポリエステル', 'BONLECILL', '', '春-秋-冬', '', 14, 1, '', '/static/images/1/clothes/gazou57.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ニット', 'NICE CLAUP', 'カジュアル、カジュアル、', '春-秋-冬', '長袖', 15, 1, '長袖', '/static/images/1/clothes/gazou58.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (6, 5, 1, 'ポリエステル', 'UNIQLO', 'きれいめ', '春-秋-冬', '長袖', 16, 1, '長袖', '/static/images/1/clothes/gazou59.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'ポリエステル', 'GU', 'きれいめ', '春-秋-冬', '長袖、ダブル', 16, 1, '長袖、ダブル', '/static/images/1/clothes/gazou60.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (4, 5, 1, 'ポリエステル', 'UNIQLO', 'きれいめ', '春-秋-冬', '長袖、ダブル', 16, 1, '長袖、ダブル', '/static/images/1/clothes/gazou61.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 15, 1, 'ニット', 'EIMY ISTOIRE', 'きれいめ', '春-秋-冬', '長袖', 17, 1, '長袖', '/static/images/1/clothes/gazou62.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'ツイード', 'FLAY I.D', 'きれいめ', '春-秋-冬', '長袖', 17, 1, '長袖', '/static/images/1/clothes/gazou63.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, 'ポリエステル', '無印良品', 'きれいめ', '冬', '長袖', 18, 1, '長袖', '/static/images/1/clothes/gazou64.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 5, 1, 'ポリエステル', 'TOMORROWLAND collection', 'きれいめ', '冬', '長袖', 18, 1, '長袖', '/static/images/1/clothes/gazou65.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'デニム', 'URBANDTYPE', 'カジュアル', '春-秋', '長袖', 19, 1, '長袖', '/static/images/1/clothes/gazou66.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'レザー', 'MASION SPECIAL', 'カジュアル', '春-秋-冬', '長袖', 20, 1, '長袖', '/static/images/1/clothes/gazou67.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (2, 15, 1, 'ポリエステル', 'KANGOL', 'カジュアル', '春-秋-冬', '長袖', 21, 1, '長袖', '/static/images/1/clothes/gazou68.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, 'ナイロン', 'HOUSTION', 'カジュアル', '春-秋-冬', '長袖', 22, 1, '長袖', '/static/images/1/clothes/gazou69.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (16, 1, 1, '22', 'Starting Over', 'カジュアル', '春-秋-冬', '長袖', 23, 1, '長袖', '/static/images/1/clothes/gazou70.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (13, 1, 1, 'ポリエステル', 'mihns closet', 'カジュアル', '冬', '長袖、ダウン', 24, 1, '長袖、ダウン', '/static/images/1/clothes/gazou71.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 5, 1, 'ポリエステル', 'center i', 'カジュアル', '冬', '長袖、ダウン', 24, 1, '長袖、ダウン', '/static/images/1/clothes/gazou72.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 15, 1, 'ポリエステル', 'Sibra', 'カジュアル', '冬', '長袖、ダウン', 24, 1, '長袖、ダウン', '/static/images/1/clothes/gazou73.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (6, 1, 1, 'ポリエステル', '無印良品', 'カジュアル', '冬', '長袖', 24, 1, '長袖', '/static/images/1/clothes/gazou74.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'ポリエステル', '無印良品', 'カジュアル', '冬', '長袖', 24, 1, '長袖', '/static/images/1/clothes/gazou75.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'ポリエステル', '無印良品', 'カジュアル', '冬', '長袖、ロングコート', 24, 1, '長袖、ロングコート', '/static/images/1/clothes/gazou76.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'AIVER', 'カジュアル', '冬', '長袖、ロングコート', 25, 1, '長袖、ロングコート', '/static/images/1/clothes/gazou77.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'POLO', 'カジュアル', '冬', '長袖', 26, 1, '長袖', '/static/images/1/clothes/gazou78.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'AOYAMA', 'きれいめ', '冬', '長袖', 27, 1, '長袖', '/static/images/1/clothes/gazou79.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (4, 1, 1, 'コットン', 'Paul Smith', '上品、きれいめ', '春-秋', 'ダブル', 28, 1, 'ダブル', '/static/images/1/clothes/gazou80.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'ETELIO', 'きれいめ', '冬', 'ロング丈、ドロップショルダー', 29, 1, 'ロング丈、ドロップショルダー', '/static/images/1/clothes/gazou81.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (6, 1, 1, 'ポリエステル', 'LUCY', 'カジュアル、ストリート', '冬', 'ダブルジップ', 30, 1, 'ダブルジップ', '/static/images/1/clothes/gazou82.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (15, 15, 1, 'ナイロン', '76', 'カジュアル、ストリート、ストリート', '秋-冬', 'ゆとりのあるシルエット', 31, 1, 'ゆとりのあるシルエット', '/static/images/1/clothes/gazou83.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (13, 15, 1, 'ナイロン', 'LOGOS', 'カジュアル、ストリート、ストリート', '春-秋-冬', 'ミドル丈', 32, 1, 'ミドル丈', '/static/images/1/clothes/gazou84.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 15, 1, 'ポリエステル', 'MLB', 'カジュアル、ストリート、ストリート', '冬', 'フードなし、刺繍', 33, 1, 'フードなし、刺繍', '/static/images/1/clothes/gazou85.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 15, 1, 'ポリエステル', 'NICE CLAUP', 'カジュアル、ストリート、ストリート', '冬', 'サテン', 34, 1, 'サテン', '/static/images/1/clothes/gazou86.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 1, 1, 'ポリエステル', 'Rocky Monroe', 'カジュアル、ストリート、ストリート', '春-秋', 'ダブルジップ、ゆとりがあるサイズ感', 35, 1, 'ダブルジップ、ゆとりがあるサイズ感', '/static/images/1/clothes/gazou87.png');

INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (13, 1, 1, 'デニム', 'UNIQLO', 'カジュアル', '春-夏-秋-冬', '長ズボン、ストレート', 39, 1, '長ズボン、ストレート', '/static/images/1/clothes/gazou91.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (12, 1, 1, 'デニム', 'UNIQLO', 'カジュアル', '春-夏-秋-冬', '長ズボン、ストレート', 39, 1, '長ズボン、ストレート', '/static/images/1/clothes/gazou92.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, 'ポリエステル', 'GU', 'カジュアル', '春-夏-秋-冬', '長ズボン、ワイドシルエット', 40, 1, '長ズボン、ワイドシルエット', '/static/images/1/clothes/gazou93.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (16, 1, 1, 'ポリエステル', 'GU', 'カジュアル', '春-夏-秋-冬', '長ズボン、ワイドシルエット', 40, 1, '長ズボン、ワイドシルエット', '/static/images/1/clothes/gazou94.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (4, 1, 1, '綿', 'UNIQLO', 'カジュアル、きれいめ　', '春-夏-秋-冬', '長ズボン、ストレート', 41, 1, '長ズボン、ストレート', '/static/images/1/clothes/gazou95.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (17, 1, 1, '綿', 'UNIQLO', 'カジュアル　', '春-夏-秋-冬', '長ズボン、ワイドシルエット', 42, 1, '長ズボン、ワイドシルエット', '/static/images/1/clothes/gazou96.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, '綿', 'UNIQLO', 'カジュアル　', '春-夏-秋-冬', '長ズボン、ストレート', 42, 1, '長ズボン、ストレート', '/static/images/1/clothes/gazou97.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 4, 1, 'ポリエステル', 'GU', 'カジュアル', '春-夏-秋-冬', '長ズボン、ツータック', 43, 1, '長ズボン、ツータック', '/static/images/1/clothes/gazou98.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (18, 4, 1, 'ポリエステル', '無印良品', 'カジュアル', '春-夏-秋-冬', '長ズボン、スカート', 44, 1, '長ズボン、スカート', '/static/images/1/clothes/gazou99.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (12, 1, 1, 'デニム', 'GU', 'カジュアル', '春-夏-秋-冬', 'マキシ丈', 45, 1, 'マキシ丈', '/static/images/1/clothes/gazou100.png');
INSERT INTO items (color_id, pattern_id, size_id, material, brand, taste, seasons, features, category_detail_id, user_id, item_name, image_path) VALUES (19, 1, 1, 'ポリエステル', 'nouvellemoi', 'きれいめ', '春-夏-秋-冬', 'マーメイドスカート', 46, 1, 'マーメイドスカート', '/static/images/1/clothes/gazou101.png');

COMMIT;
